# These are supported funding model platforms

github: [anoited007, ebenezergraham]
patreon: ebenezergraham
open_collective: # Replace with a single Open Collective greeting
ko_fi: # Replace with a single Ko-fi greeting
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
